### ISSUE TITLE
mu-cite.el fails with void-function defun-maybe-cond

### ISSUE THREAD

**Issue by tats** [cvs-m17n-org/MU-CITE#4]
With recent APEL-LB <https://github.com/wanderlust/apel> (2020-10-31),
loading mu-cite.el fails as follows.

```
$ emacs -batch -Q -L ../apel-wl -L ../flim-wl -L . -l mu-cite.el
Eager macro-expansion failure: (void-function defun-maybe-cond)
Eager macro-expansion failure: (void-function defun-maybe-cond)
Symbol’s function definition is void: defun-maybe-cond
```

Because poem.el doesn't load pym.el anymore.

Adding `(require 'pym)` to mu-cite.el prevents this problem.

**Comment by cvs-m17n-org** [comment]
Confirmed and pushed the fix.  Thank you for pointing this out.
